# docker run --rm -it -v $PWD:/project -w /project snapcore/snapcraft:stable snapcraft clean
# docker run --rm -it -v $PWD:/project -w /project snapcore/snapcraft:stable snapcraft
# snapcraft push --release edge *.snap

name: test-io-uziot
version: '0.0.1.alpha'
summary: Application for simple socket and io console app
description: Test IO UZIOT is a free and open source software application that sending and receiving binary data over socket and io on console app.

confinement: devmode

apps:
  test-io-uziot:
#    command: bin/IOTestStarter.sh
    command: ulimit -c unlimited
    command: usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.library.path=$SNAP/bin/jre/ -cp $SNAP/bin/IOTestStarter.jar:$SNAP/bin/jre-ext/RXTXcomm.jar com.mycompany.supercommlistener.Main
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $SNAP/usr/lib/jvm/default-java/bin:$PATH
    plugs: [home]

parts:
  test-io-uziot:
    source: .
    plugin: dump
    organize:
      target/test-io-uziot-1.0-SNAPSHOT-jar-with-dependencies.jar: bin/IOTestStarter.jar
      snap-files/IOTestStarter.sh: bin/IOTestStarter.sh
      snap-files/x86_64_rxtx/librxtxSerial.so: bin/jre/librxtxSerial.so
      snap-files/x86_64_rxtx/RXTXcomm.jar: bin/jre-ext/RXTXcomm.jar
    build-packages:
    - ca-certificates
    - ca-certificates-java
    - openjdk-8-jre-headless
    stage-packages: [openjdk-8-jre-headless]